### PR TITLE
Reviewed and adopted for "normal" Debian Jessie installation.

### PR DESCRIPTION
**Pull request by ypid**
- Untested on Qubes OS.

### CODE REVIEW

**Comment by adrelanos** [comment]
https://www.whonix.org/forum/index.php/topic,97.msg10072.html#msg10072

**Comment by troubadoour** [comment]
Unfortunately, the branch `fixed_for_normal_debian_jessie` does not work in "Whonix" Debian jessie. 
A couple of issues:
- we do need "@{HOME}/.config/*\* rw," for "/home/user/.config/oxygen-gtk/argb-apps.conf", the first file of a list which pop denied messages.
- "/dev/vboxuser rw," is required because Whonix is working in VirtualBox too, along with Qubes and KVM.

It looks like we have to keep a specific profile.

**Comment by ypid** [comment]
Thanks for the review. Not sure about the separate profile thing.
1. Sure. That was my question. I just thought it was a pretty bad idea to include the whole `.config/**`. Fixed.
2. Still curious about that. What does `auditd` say about the `/dev/vboxuser` file. I mean `icedove` also works when it is not virtualized …
   PS: KVM and Qubes OS don’t use Virtualbox.

**Comment by troubadoour** [comment]
Have updated the Whonix profile with `.config/oxygen-gtk/*`, as well as narrowing permissions in `.cache`.

`/dev/vboxuser` is required only when Icedove is run in VirtualBox. Removing the line is not fatal, it only pops a denied message. This line will not prevent the profile from working in a host environment, or in KVM and Qubes.

auditd reports more or less the same as kern.log:
`name="/dev/vboxuser"comm="icedove" requested_mask="rw" denied_mask="rw" fsuid=1000 ouid=0`

**Comment by ypid** [comment]
Thanks for the review. I updated the PR.

**Comment by adrelanos** [comment]
> `# /dev/vboxuser rw,`

We don't want denied messages popping up.
- How does `/dev/vboxuser rw,` harm to non-VirtualBox systems?
- We could consider `/dev/vboxuser rw,` -> `deny /dev/vboxuser rw,`.

**Comment by ypid** [comment]
> deny /dev/vboxuser rw,

Would be worth a trial. Not sure if it is harmful but in my opinion unneeded.

**Comment by troubadoour** [comment]
Added some commits in your branch after testing in VirtualBox (Whonix 11, Debian jessie), KVM (Whonix 10, Debian wheezy) and my host (Debian jessie). I cannot install Qubes R3 in my machine, so it's untested.

Some commits are cosmetic, another one removes some early development lines (too permissive).
https://github.com/troubadoour/apparmor-profile-icedove/tree/fixed_for_normal_debian_jessie

One way or the other, we're going to merge this branch in Whonix (I'm using it now). The version above is working in all tested environment without harming any one.

Note that Whonix uses apparmor-notify , implying that any denied message will pop up on the desktop.

**Comment by adrelanos** [comment]
Doesn't work any worse in Qubes than before.
Please merge https://github.com/troubadoour/apparmor-profile-icedove/tree/fixed_for_normal_debian_jessie into master whenever you're ready.

**Comment by troubadoour** [comment]
Done, with some additional commits.
Had an issue with merge conflicts, hence the git revert.

**Comment by adrelanos** [comment]
Merged.

**Comment by adrelanos** [comment]
@ypid is there still something you want merged? In this case, please rebase.

**Comment by adrelanos** [comment]
Minor commit on top by me.

`replace i686 with wildcard *`:
https://github.com/Whonix/apparmor-profile-icedove/commit/8c12286bef0f1b5dcd508550f51b51893e825d80

**Comment by troubadoour** [comment]
Merged.

**Comment by ypid** [comment]
Looks good. Thanks for the review and additional work.

**Pull request closed without merging**
